name: CI
on: [push]
jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "^22"
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Format
        run: yarn run fmt-check

      - name: Lints
        run: yarn run lint-check

      - name: Typecheck
        run: yarn typecheck

      - name: Tests
        run: yarn test
        env:
          CODECOV: true
          NODE_ENV: test
      - name: Build
        run: yarn build
